### ISSUE TITLE
How do I specify AM/PM in the date field?

### ISSUE THREAD

**Issue by terrybarth** [Jako/multiTV#130] opened 2015-03-22 21:29 UTC
I've used MIGX for Revo on many projects. I have client running EVO and need similar functionality so I am really excited to see this Extra! Thank you!

I'm trying out the event example. I want to specify the time and date for an event. I will have various events from morning to late evening. Using the slider, the time cycles 12:00 - 11:00 and then 12:00 - 11:00. I expected it to cycle 0:00 - 24:00.  If I manually edit the date/time value to 15:00, it reverts to 3:00 and the slider is close to the left (presumably AM).

So how do I specify AM/PM?

Thank you!

**Comment by Jako** [comment] 2015-04-29 06:19
I don't have a timepicker shown in my installation. Have you patched the language file and/or the multitv.js to show that? Or do you have another Extra that uses jquery datetimepicker and sets own options for that jquery plugin?

**Comment by terrybarth** [comment] 2015-04-29 14:33
Jako

Thanks for getting back to me

I'm using a fresh install of evo with just the default packages installed. The only thing I've added is the multiTV snippet. I've made not other changes.

This is the call

[!multiTV? &tvName=`event`
&docid=`[*id*]` &tplConfig=``
&outerTpl=`@CODE:<ul>((wrapper))</ul>`
&rowTpl=`@CODE:<div>((event)), ((location)), ((time))</div>`
&display=`9` &where=`{"event:>":"23-04-2015 6:00:00"}` !]

Here is the event.config.inc.php file. I modified only the caption.

<?php
$settings['display'] = 'horizontal';
$settings['fields'] = array(
    'event' => array(
        'caption' => 'Event Name',
        'type' => 'date',
        'width' => '160'
    ),
    'location' => array(
        'caption' => 'Location',
        'type' => 'text',
        'width' => '180'
    ),
    'price' => array(
        'caption' => 'Price',
        'type' => 'text',
        'width' => '90'
    )
);
$settings['templates'] = array(
    'outerTpl' => '<div class="events">[+wrapper+]</div>',
    'rowTpl' => '<div class="event">[+event+], [+location+] ([+price+])</div>'
);

Here's what I see.

![2015-04-29_0932](https://cloud.githubusercontent.com/assets/526281/7393326/b0427372-ee52-11e4-9eb0-0909fde3b6eb.png)

**Comment by Jako** [comment] 2015-04-29 19:14
O.K. There are two bugs with that date input. First one with the 12/24 hours and the second one with multiple multiTV using a jquery.datetimepicker.

**Comment by terrybarth** [comment] 2015-04-29 19:38
Jako

Anything I can/should do?


  [image: photo]  Terry Barth
Terry Barth Design
 Phone: 612 859 2453
 Email: terrybarth@terrybarth.com
 Website: www.terrybarthdesign.com
    Get a signature like this:
<https://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>
Click
here!
<https://ws-stats.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8/dXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9>

**Comment by Jako** [comment] 2015-05-05 17:43
Sorry, I am quite busy at the moment. Have no time to debug that now. I think the second bug is caused by calling the multiTV scripts twice on the resource editing page. But I have no idea for the AM/PM issue. Maybe a different jquery date/timepicker script could be an option.

**Comment by Jako** [comment] 2015-05-31 12:28
Fixed with https://github.com/Jako/multiTV/commit/30c088fbfd13d566acbb509ece39aafada6ec88b

**Closed by Jako** 2015-05-31 12:28 UTC
