### ISSUE TITLE
sorting in datatable config

### ISSUE THREAD

**Issue by Fr3ddy7** [Jako/multiTV#163] opened 2016-09-04 19:40 UTC
datatable config (last evo from git + last multitv) 

sorting not working, 3 sites. after saving nothing happens, everything is back in its place

**Comment by Deesen** [comment] 2016-09-05 04:15
I can confirm. After moving a row a error pops up in console: `TypeError: ui.item.context is undefined`

**Comment by Deesen** [comment] 2016-09-05 04:36
@Jako : I am not sure what is the root-cause of this issue and since when it happened. When I do the following, row-reordering works again: In `jquery-dataTables.rowReordering-1.1.0.js`, line 222-end I replaced `ui.item.context.id` by `ui.item[0].id`.

**Comment by Fr3ddy7** [comment] 2016-09-06 13:33
@Jako ?)

**Comment by Deesen** [comment] 2016-09-06 15:23
I guess I found the reason. On 19.07. jQuery got updated to v3.1 and is loaded by default in MODX Manager. So it seems jquery-ui-1.10.4.custom.min.js is not compatible with 3.1.

**Comment by Fr3ddy7** [comment] 2016-09-13 09:22
just I tried it in another manager theme, modxpress
everything is working. No errors and conflicts. Mystic)

switch to modxre - does not work

**Comment by Fr3ddy7** [comment] 2016-09-13 09:30
+ in template connect the old version 1.8.3 :(

**Comment by dmi3yy** [comment] 2016-10-27 21:25
https://github.com/modxcms/evolution/issues/869 

its the same bug

**Comment by Deesen** [comment] 2016-10-28 04:19
Sure? Our sort-icons where visible and useable, but the new order would not be saved to DB.

**Comment by Jako** [comment] 2017-03-31 08:44
Should be fixed now.

**Closed by Jako** 2017-03-31 08:44 UTC
Labels: bug

**Comment by Deesen** [comment] 2017-03-31 08:54
Thanks!

**Comment by Fr3ddy7** [comment] 2017-03-31 08:56
Thanks!

**Comment by Jako** [comment] 2017-04-02 07:47
Who updates the package on http://extras.evolution-cms.com/ ?

**Comment by dmi3yy** [comment] 2017-04-02 08:34
I do this tomorrow

Отправлено с iPhone
